# あるフローがなんらかの例外をスローすることを期待するテスト
例えば、コピーアンドペーストなど、なんらかの手段により電卓が許容しない桁数の数値が打ち込まれた時は、エラーをスローする必要があります。
このように、特定の条件下でエラーが適切にスローされることを確認するテストは、どのように実装するのでしょうか。

## 電卓が許容しない桁数の数値が打ち込まれた時は、エラーをスローする

桁数制限を持つ電卓クラスを準備しましょう。
Calculatorは、10桁を超える数値が入力された場合にCalculatorErrorをスローします。
```swift
enum CalculatorError: Error {
    case divideByZero
    case tooManyDigits // 桁数制限に関するエラー
}

class Calculator {
    let maxDigits: Int = 10 // 最大桁数
    
    func add(_ a: Double, _ b: Double) -> Double {
        return a + b
    }
    
    func inputNumber(_ number: String) throws -> Double {
        guard number.count <= maxDigits else {
            throw CalculatorError.tooManyDigits
        }
        guard let value = Double(number) else {
            throw CalculatorError.tooManyDigits // 無効な数値形式
        }
        return value
    }
}

```

## テストケースを実装する
電卓が許容しない桁数の数値が入力された際に、例外がスローされることを確認するテストを実装します。
このケースにおいて便利なアサーションが`XCTAssertThrowsError`です。
`XCTAssertThrowsError`は、なんらかの例外をスローすることを期待します。

```swift
    func testInputNumberTooManyDigits() {
        let calculator = Calculator()
        
        // 11桁の数値を入力するテスト
        XCTAssertThrowsError(try calculator.inputNumber("12345678901")) { error in
            XCTAssertEqual(error as? CalculatorError, CalculatorError.tooManyDigits)
        }
        
        // 有効な数値の入力テスト
        XCTAssertNoThrow(try calculator.inputNumber("1234567890")) // 10桁の数値
    }
```

グリーンになりましたか？